Packaging for app bundle (#934)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -146,10 +146,23 @@ jobs:
         key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
 
     - run: make deps
+
     - id: build
       run: make package-builder
+
     - name: package
-      run: ${{ steps.build.outputs.binary }} make -debug --hostname=localhost --enroll_secret=secret
+      id: run-package-builder
+      run: ${{ steps.build.outputs.binary }} make -debug --hostname=localhost --enroll_secret=secret --launcher_version=nightly --output_dir=./
+
+    - name: Test install macOS
+      if: ${{ contains(matrix.os, 'macos') }}
+      run: |
+        # Check that we can install
+        sudo installer -dumplog -pkg ./launcher.darwin-launchd-pkg.pkg -target /
+        # Quick check that at least a couple of the files we expect now exist
+        if [ ! -f /Library/LaunchDaemons/com.launcher.launcher.plist ]; then echo "missing launchd entry" && exit 1; fi
+        if [ ! -f /usr/local/launcher/bin/osqueryd ]; then echo "missing osquery binary" && exit 1; fi
+        if [ ! -f /usr/local/launcher/bin/Kolide.app/Contents/MacOS/launcher ]; then echo "missing launcher binary" && exit 1; fi
 
   # This job is here as a github status check -- it allows us to move
   # the merge dependency from being on all the jobs to this single
