Adjust CI to check if launcher --version succeeds rather than check its output.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -79,24 +79,25 @@ jobs:
     - name: Test
       run: make test
 
-    # Launcher should always print its version info when called with `version` -- this is a quick
+    # Launcher should always successfully run and exit cleanly when called with `version` -- this is a quick
     # check to ensure that launcher can update to this build.
     - name: Test build - macOS and ubuntu
       if: ${{ contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu') }}
       run: |
-        if [[ $(./build/launcher --version) != *"launcher - version"* ]]; then
-          echo "launcher version did not print version information"
+        if ! ./build/launcher --version; then
+          echo "launcher.exe --version failed"
           exit 1
         fi
 
-    # Launcher should always print its version info when called with `version` -- this is a quick
+    # Launcher should always successfully run and exit cleanly when called with `version` -- this is a quick
     # check to ensure that launcher can update to this build.
     - name: Test build - Windows
       if: ${{ contains(matrix.os, 'windows') }}
       shell: powershell
       run: |
-        if(-not (.\build\launcher.exe --version | findstr "launcher - version")) {
-          throw "launcher.exe version did not print version information"
+        .\build\launcher.exe --version
+        if( !$? ) {
+          throw "launcher.exe --version failed"
         }
 
     - name: Upload Build - Windows
